### ISSUE TITLE
jaeger exporter

### ISSUE THREAD

**Issue by ibtesamlatif2997** [jufab/opentelemetry-angular-interceptor#124]
Hi,

I am unable to identify how to export the spans to jaeger. 

It is mentioned in **Jaeger Propagator Configuration**, we need to specify the **custom headers**. But I am unable to identify how to pass my Jaeger collector URL in **Jaeger Propagator Configuration**.

Please help

**Comment by jufab** [comment]
Hi @ibtesamlatif2997 ,

There is no jaeger exporter in this project because Jaeger exporter is only for node.js and not http.

more information here => https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-exporter-jaeger

Maybe you can use Zipkin to your Jaeger collector or use an Otel collector to exporte to your Jaeger collector (see collector configuration in this project).
